spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/moods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    &AllowPublicKeyRetrieval=True
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#      redis 配置
  redis:
    host: 47.98.192.167
    port: 6379
    password: 1234
server:
  port: 8800
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://47.98.192.167:3306/moods?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #    &AllowPublicKeyRetrieval=True
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    host: 47.98.192.167
    port: 6379
    password: 1234
server:
  port: 8800